announce = false
debug = true
description = 'Mano tutorial serveris'
gamemode = 'Freeroam'
host = '127.0.0.1'
language = 'lt'
modules = [ 'js-module', 'csharp-module' ]
name = 'Tutorial'
players = 128
port = 7788
resources = [ 'chat', 'tutorial', 'imports/m5e34', 'map/baznycia' ]
website = 'example.com'