announce = false
debug = true
description = 'Mano tutorial serveris'
gamemode = 'Freeroam'
host = '0.0.0.0'
language = 'lt'
modules = [ 'js-module', 'csharp-module' ]
name = 'Tutorial'
players = 128
port = 7788
resources = [ 'chat', 'tutorial', 'imports/m5e34','imports/bmw_m4', 'map/baznycia' ]
website = 'example.com'

[csharp-module]
disableDependencyDownload = true