files = [ 'stream/assets/*' ]

[gxt]

[meta]
'stream/carvariations.meta' = 'VEHICLE_VARIATION_FILE'
'stream/dlctext.meta' = 'TEXTFILE_METAFILE'
'stream/handling.meta' = 'HANDLING_FILE'
'stream/vehiclelayouts.meta' = 'VEHICLE_LAYOUTS_FILE'
'stream/vehicles.meta' = 'VEHICLE_METADATA_FILE'